package app

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/RawH2O/agent-hook-kit/pkg/hookkit"
)

// HookConfigOptions controls the generated Codex hooks.json entry.
type HookConfigOptions struct {
	Provider      string
	Command       string
	Matcher       string
	Timeout       int
	StatusMessage string
	Description   string
}

// HookDefinition is the provider-neutral metadata needed to materialize one
// command hook. A platform/GitOps layer can build these definitions from YAML
// without importing the business rule implementation.
type HookDefinition struct {
	Name          string
	Command       string
	Events        []hookkit.Event
	Matcher       string
	Timeout       int
	StatusMessage string
}

// GenerateHooks returns a Codex hooks.json document for the events declared
// by rules. Command is the complete command Codex should execute.
func GenerateHooks(rules []hookkit.Rule, options HookConfigOptions) ([]byte, error) {
	if strings.ToLower(strings.TrimSpace(options.Provider)) != "codex" {
		return nil, fmt.Errorf("hooks.json generation currently supports provider %q only; want codex", options.Provider)
	}
	if strings.TrimSpace(options.Command) == "" {
		return nil, fmt.Errorf("hook command is required")
	}
	events, err := declaredEvents(rules)
	if err != nil {
		return nil, err
	}
	if len(events) == 0 {
		return nil, fmt.Errorf("cannot generate hooks.json without rules")
	}

	definitions := []HookDefinition{{
		Name:          "registered-rules",
		Command:       options.Command,
		Events:        events,
		Matcher:       options.Matcher,
		Timeout:       options.Timeout,
		StatusMessage: options.StatusMessage,
	}}
	return GenerateHookDefinitions(definitions, options.Description)
}

// GenerateHookDefinitions returns a Codex hooks.json document for generic
// command definitions. Each definition becomes one matcher group per event.
// This is the API intended for a GitOps/platform layer that stores hook
// metadata separately from the Go binary containing the business logic.
func GenerateHookDefinitions(definitions []HookDefinition, description string) ([]byte, error) {
	if len(definitions) == 0 {
		return nil, fmt.Errorf("cannot generate hooks.json without hook definitions")
	}

	hooks := make(map[string][]any)
	seenNames := make(map[string]struct{}, len(definitions))
	for index, definition := range definitions {
		name := strings.TrimSpace(definition.Name)
		if name == "" {
			return nil, fmt.Errorf("hook definition %d has an empty name", index)
		}
		if _, exists := seenNames[name]; exists {
			return nil, fmt.Errorf("duplicate hook definition name %q", name)
		}
		seenNames[name] = struct{}{}
		if strings.TrimSpace(definition.Command) == "" {
			return nil, fmt.Errorf("hook definition %q has an empty command", name)
		}
		if definition.Timeout < 0 {
			return nil, fmt.Errorf("hook definition %q has a negative timeout", name)
		}
		if len(definition.Events) == 0 {
			return nil, fmt.Errorf("hook definition %q declares no events", name)
		}

		seenEvents := make(map[hookkit.Event]struct{}, len(definition.Events))
		for _, event := range definition.Events {
			if event == "" || event == "*" {
				return nil, fmt.Errorf("hook definition %q declares unsupported event %q", name, event)
			}
			if _, exists := seenEvents[event]; exists {
				return nil, fmt.Errorf("hook definition %q declares event %q more than once", name, event)
			}
			seenEvents[event] = struct{}{}

			handler := map[string]any{
				"type":    "command",
				"command": definition.Command,
			}
			if definition.Timeout > 0 {
				handler["timeout"] = definition.Timeout
			}
			if definition.StatusMessage != "" {
				handler["statusMessage"] = definition.StatusMessage
			}
			group := map[string]any{
				"hooks": []any{handler},
			}
			if definition.Matcher != "" {
				group["matcher"] = definition.Matcher
			}
			hooks[string(event)] = append(hooks[string(event)], group)
		}
	}

	if description == "" {
		description = "Generated by agent-hook-kit"
	}
	document := map[string]any{
		"description": description,
		"hooks":       hooks,
	}
	return marshalJSON(document)
}

// InstallHooks merges generated entries into an existing Codex hooks.json.
// Existing hooks are preserved, and an identical command is not duplicated.
func InstallHooks(path string, rules []hookkit.Rule, options HookConfigOptions) error {
	generated, err := GenerateHooks(rules, options)
	if err != nil {
		return err
	}
	return mergeHooksFile(path, generated)
}

// InstallHookDefinitions merges generic command definitions into an existing
// Codex hooks.json. Existing hooks are preserved, and an identical command is
// not duplicated.
func InstallHookDefinitions(path string, definitions []HookDefinition, description string) error {
	generated, err := GenerateHookDefinitions(definitions, description)
	if err != nil {
		return err
	}
	return mergeHooksFile(path, generated)
}

func mergeHooksFile(path string, generated []byte) error {
	document := make(map[string]any)
	if data, readErr := os.ReadFile(path); readErr == nil {
		if err := json.Unmarshal(data, &document); err != nil {
			return fmt.Errorf("parse hooks config %s: %w", path, err)
		}
	} else if !os.IsNotExist(readErr) {
		return fmt.Errorf("read hooks config %s: %w", path, readErr)
	}

	var additions map[string]any
	if err := json.Unmarshal(generated, &additions); err != nil {
		return fmt.Errorf("parse generated hooks config: %w", err)
	}
	if description, ok := additions["description"].(string); ok {
		if _, exists := document["description"]; !exists {
			document["description"] = description
		}
	}

	hooks, err := hookTable(document)
	if err != nil {
		return fmt.Errorf("merge hooks config %s: %w", path, err)
	}
	generatedHooks, ok := additions["hooks"].(map[string]any)
	if !ok {
		return fmt.Errorf("generated hooks config has no hooks table")
	}
	for event, rawGroups := range generatedHooks {
		groups, err := hookGroups(hooks, event)
		if err != nil {
			return fmt.Errorf("merge event %s: %w", event, err)
		}
		newGroups, ok := rawGroups.([]any)
		if !ok {
			return fmt.Errorf("generated event %s is not an array", event)
		}
		for _, group := range newGroups {
			if !containsCommand(groups, group) {
				groups = append(groups, group)
			}
		}
		hooks[event] = groups
	}

	data, err := marshalJSON(document)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create hooks config directory: %w", err)
	}
	if err := os.WriteFile(path, data, 0o600); err != nil {
		return fmt.Errorf("write hooks config %s: %w", path, err)
	}
	return nil
}

func declaredEvents(rules []hookkit.Rule) ([]hookkit.Event, error) {
	seen := make(map[hookkit.Event]struct{})
	for _, rule := range rules {
		if rule == nil {
			return nil, fmt.Errorf("cannot generate hooks.json from a nil rule")
		}
		if rule.ID() == "" {
			return nil, fmt.Errorf("cannot generate hooks.json from a rule without an ID")
		}
		if len(rule.Events()) == 0 {
			return nil, fmt.Errorf("rule %q does not declare any events", rule.ID())
		}
		for _, event := range rule.Events() {
			if event == "" || event == "*" {
				return nil, fmt.Errorf("rule %q declares unsupported event %q for hooks.json", rule.ID(), event)
			}
			seen[event] = struct{}{}
		}
	}
	events := make([]hookkit.Event, 0, len(seen))
	for event := range seen {
		events = append(events, event)
	}
	sort.Slice(events, func(left, right int) bool { return events[left] < events[right] })
	return events, nil
}

func hookTable(document map[string]any) (map[string]any, error) {
	if raw, exists := document["hooks"]; exists {
		hooks, ok := raw.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("hooks is not an object")
		}
		return hooks, nil
	}
	hooks := make(map[string]any)
	document["hooks"] = hooks
	return hooks, nil
}

func hookGroups(hooks map[string]any, event string) ([]any, error) {
	raw, exists := hooks[event]
	if !exists {
		return nil, nil
	}
	groups, ok := raw.([]any)
	if !ok {
		return nil, fmt.Errorf("event value is not an array")
	}
	return groups, nil
}

func containsCommand(groups []any, generated any) bool {
	generatedGroup, ok := generated.(map[string]any)
	if !ok {
		return false
	}
	generatedHandlers, _ := generatedGroup["hooks"].([]any)
	for _, group := range groups {
		groupObject, ok := group.(map[string]any)
		if !ok {
			continue
		}
		handlers, _ := groupObject["hooks"].([]any)
		for _, handler := range handlers {
			for _, generatedHandler := range generatedHandlers {
				current, currentOK := handler.(map[string]any)
				wanted, wantedOK := generatedHandler.(map[string]any)
				if currentOK && wantedOK && current["type"] == "command" && current["command"] == wanted["command"] {
					return true
				}
			}
		}
	}
	return false
}

func marshalJSON(value any) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode hooks config: %w", err)
	}
	return append(data, '\n'), nil
}
